# Change these first
owner: Ryanjiena # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Coding
    url: https://coding.net
  - name: Gitee
    url: https://gitee.com
  - name: Github
    url: https://github.com
  - name: Github Status
    url: https://www.githubstatus.com
  - name: Ryanjie Blog
    url: https://www.ryanjie.cn
  - name: Ryanjie Drive
    url: https://gd.ryanjie.cn
  - name: Ryanjie Github
    url: https://git.ryanjie.cn
  - name: Ryanjie Google
    url: https://gg.fgh.workers.dev
  - name: Ryanjie Google Scholar
    url: https://gs.ryanjie.cn
  - name: Ryanjie Hexo Blog
    url: https://hexo.ryanjie.cn
  - name: Ryanjie Img
    url: https://img.ryanjie.cn
  - name: Ryanjie Learn
    url: https://learn.ryanjie.cn
  - name: Ryanjie Movie
    url: https://movie.ryanjie.cn
  - name: Ryanjie Onedrive
    url: https://file.ryanjie.cn
  - name: Ryanjie Pic
    url: https://pic.ryanjie.cn
  - name: Ryanjie Pornhub
    url: https://ph.ryanjie.cn
  - name: Ryanjie Profile
    url: https://m.ryanjie.cn
  - name: Ryanjie RSSHUB
    url: https://rss.ryanjie.cn
  - name: Ryanjie Status
    url: https://ss.ryanjie.cn
  - name: Ryanjie Uptime Robot Status
    url: https://status.ryanjie.cn
  - name: Ryanjie Wikipedia EN
    url: https://ewp.ryanjie.cn
  - name: Ryanjie Wikipedia ZH
    url: https://zwp.ryanjie.cn
  - name: Ryanjie WorkProject
    url: https://project.ryanjie.cn
  # - name: Secret Site
  #   url: $SECRET_SITE

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://cdn.jsdelivr.net/gh/Ryanjiena/Ryanjiena@master/icon/Ryanjiena.svg
  favicon: https://cdn.jsdelivr.net/gh/Ryanjiena/icon@master/png/site/ryanjie.png
  name: Upptime
  introTitle: Uptime Status 
  introMessage: Stay Simple.
  navbar:
    - title: Status
      href: /
    - title: Uptime Robot
      href: https://ss.ryanjie.cn
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
#   commitAuthorName: "RyanjienaBot"
#   commitAuthorEmail: "zxj@outlook.sg"
  
